services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    network_mode: bridge
    ports:
      - 9000:9000
    restart: unless-stopped
    volumes:
      - $PWD/tl:/var/opt/thelounge
      - $PWD/src:/var/opt/thelounge/packages/thelounge-plugin-ntfy/src
      - $PWD/index.js:/var/opt/thelounge/packages/thelounge-plugin-ntfy/index.js
      - $PWD/package.json:/var/opt/thelounge/packages/thelounge-plugin-ntfy/package.json
      - $PWD/package-lock.json:/var/opt/thelounge/packages/thelounge-plugin-ntfy/package-lock.json

# Installation: su node -c "thelounge install file:/var/opt/thelounge/packages/thelounge-plugin-ntfy"
# Removal: su node -c "thelounge uninstall thelounge-plugin-ntfy"
